# Generated by Django 5.0.6 on 2024-06-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
