# Generated by Django 5.0.6 on 2024-06-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='img_url',
            field=models.TextField(),
        ),
    ]
