# Generated by Django 5.0.6 on 2024-06-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='img_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
