# Generated by Django 5.0.6 on 2024-06-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_img_url'),
        ('movie', '0003_alter_movie_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='actor.actor'),
        ),
    ]
