# Generated by Django 5.0.1 on 2024-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uta_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utauser',
            name='favorite_route',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
