# Generated by Django 5.0.1 on 2024-05-06 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uta_user', '0002_alter_utauser_favorite_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FaqMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_text', models.TextField()),
                ('faqs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uta_user.faqs')),
            ],
        ),
    ]
