# Generated by Django 5.0.1 on 2024-04-30 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20)),
                ('route_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UtaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_route', models.CharField(max_length=30)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('my_routes', models.ManyToManyField(related_name='my_routes', to='uta_user.route')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uta_user.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uta_user.utauser')),
            ],
        ),
    ]
