# Generated by Django 5.0.1 on 2024-05-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uta_user', '0003_faqs_faqmain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faqs',
            new_name='Faq',
        ),
    ]
