# Generated by Django 5.0.1 on 2024-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uta_user', '0004_rename_faqs_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqmain',
            name='active',
            field=models.BooleanField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
