# Generated by Django 5.0.6 on 2024-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_to', models.CharField(max_length=100)),
                ('airport_from', models.CharField(max_length=100)),
                ('aircraft_id', models.IntegerField()),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('departure_gate', models.IntegerField()),
                ('arrival_gate', models.IntegerField()),
                ('duration_min', models.IntegerField()),
            ],
        ),
    ]
