# Generated by Django 5.0.6 on 2024-06-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_alter_aircraft_capacity_alter_aircraft_type'),
        ('airport', '0002_remove_airport_id_alter_airport_airport_code_and_more'),
        ('employee', '0002_alter_employee_first_name_alter_employee_job_title_and_more'),
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='aircraft_id',
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_flights', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_flights', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_gate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_gate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FlightEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='emmployee',
            field=models.ManyToManyField(through='flight.FlightEmployee', to='employee.employee'),
        ),
    ]
